apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: rdb-configmap
    literals:
      - RDB_HOST=
      - RDB_HOST_WRITE=
      - RDB_HOST_RO=
      - RDB_PORT=
      - RDB_DATABASE=
secretGenerator:
  - name: aurora
    envs:
      - secret_aurora