apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '5000'
    spec:
      containers:
        - name: app
          image: app
          ports:
            - containerPort: 5000
          readinessProbe:
            timeoutSeconds: 5
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 5000
          livenessProbe:
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 10
            httpGet:
              path: /actuator/health
              port: 5000
          resources:
            requests:
              memory: 800Mi
            limits:
              memory: 800Mi
          envFrom:
            - configMapRef:
                name: rdb-configmap
            - configMapRef:
                name: redis-info-configmap
            - secretRef:
                name: api-gateway-secret
          env:
            - name: SERVER_PORT
              value: "5000"