apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- role.yaml
- role-binding.yaml
- service-account.yaml
patches:
  - path: patch.yaml
    target:
      kind: Deployment
  - path: datadog.yaml
    target:
      kind: Deployment
images:
- name: app
  newName: ghcr.io/luckypenny/api-gateway
  newTag: GIT-c7e4a03

secretGenerator:
  - name: api-gateway-secret
    literals:
      - RDB_USERNAME=
      - RDB_PASSWORD=