apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- patch.yaml
images:
- name: app
  newName: ghcr.io/luckypenny/web-react
  newTag: prod-web-react-2d86de5